version: '2'

services:
    exp_database:
        image: mysql:5.6
        container_name: exp_database
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: database_base
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - "13308:3306"
        networks:
            - project-network

    exp_redis:
         image: redis:3.2.6
         container_name: exp_redis
         hostname: redis
         networks:
             - project-network

    exp_php71:
        container_name: exp_php71
        hostname: exp-web-container
        networks:
            - project-network
        build:
            context: ./../../
            dockerfile: ./docker/php71/Dockerfile
            args:
                userId: ${USER_ID}
                groupId: ${GROUP_ID}
        depends_on:
            - exp_database
            - exp_redis
        volumes:
            - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
            - ./../../:/var/www/application
        environment:
            - SSH_AUTH_SOCK
            - PHP_IDE_CONFIG
        working_dir: /var/www/application

    exp_nginx:
        image: nginx:latest
        container_name: exp_nginx
        hostname: exp_nginx
        networks:
            - project-network
        depends_on:
            - exp_php71
        ports:
            - "8775:80"
            - "8776:443"
        volumes:
            - ./../../:/var/www/application
            - ./../../docker/template/nginx/vhost/site.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/application

networks:
    project-network:
        driver: bridge